# Generated by Django 3.2.23 on 2025-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "student_management_app",
            "0006_alter_customuser_first_name_assignment_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentsubmission",
            old_name="created_at",
            new_name="submitted_at",
        ),
        migrations.RenameField(
            model_name="notificationstaffs",
            old_name="stafff_id",
            new_name="staff_id",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="staff_id",
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[("submitted", "Submitted"), ("graded", "Graded")],
                default="submitted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submission_file",
            field=models.FileField(upload_to="assignments/submissions/"),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment_id", "student_id")},
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="submission_date",
        ),
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="updated_at",
        ),
    ]
